# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dusk Explorers
email: jazzinghen@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Like the two blogs before this, this is meant to be a place where I
  write down stuff that happens to me just to vent or just to show people
  far away what's happening to me.
  I sometime takes some pictures and I would like to show them, adding a
  comment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jazzinghen.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

locale: "en"

twitter:
  username: "jazzinghen"

author:
  name      : "Jazzinghen"
  avatar    : "/assets/images/avatar.jpg"
  bio       : "Keeping your target in sight might lead you to reach it."
  location  : "Trento - Italy"
  email     : # optional
  linkedin  : "jazzinghen"
  twitter   : "jazzinghen"
  github    : "Jazzinghen"
  steam     : "Jazzinghen"

repository: "Jazzinghen/DayStriders"

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate

minimal_mistakes_skin: dark

paginate: 5

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: false
      share: true
      elated: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
